import type { Listing } from '@/lib/types';
import { FX_PYG_USD } from '@/lib/config';

/**
 * The single seed file. In Phase 1 this is the entire "database".
 *
 * Nothing in the app imports this file directly except `lib/listings-repo.ts`
 * (the data-source seam). To move to Supabase in Phase 2 you replace the repo
 * bodies — this file simply stops being read. See README.
 *
 * `precioGs` is derived from `precioUSD` at the fixed FX rate so the two can
 * never drift; edit only `precioUSD`.
 */

type SeedListing = Omit<Listing, 'precioGs'>;

const seed: SeedListing[] = [
  // ───────────────────────────────────────── Featured (destacada: true) ────
  {
    id: 'a1b2',
    slug: 'casa-moderna-en-venta-villa-morra-asuncion-a1b2',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa moderna con piscina en Villa Morra',
    descripcion:
      'Residencia de diseño contemporáneo en el corazón de Villa Morra, sobre una calle tranquila y arbolada. Amplios ambientes integrados, abundante luz natural y terminaciones de primera calidad. El fondo cuenta con piscina, quincho y un jardín cuidado, ideal para recibir.',
    precioUSD: 485000,
    barrio: 'Villa Morra',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 4,
    banos: 4,
    cocheras: 3,
    superficieConstruida: 420,
    superficieTerreno: 600,
    caracteristicas: [
      'Piscina',
      'Quincho',
      'Aire acondicionado',
      'Seguridad 24hs',
      'Jardín',
      'Dependencia de servicio',
    ],
    coordenadas: { lat: -25.2932, lng: -57.5781 },
    imagenes: [
      'prop1-1.jpg',
      'prop1-2.jpg',
      'prop1-3.jpg',
      'prop1-4.jpg',
      'prop1-5.jpg',
      'prop1-6.jpg',
      'prop1-7.jpg',
      'prop1-8.jpg',
    ],
    destacada: true,
    destacadaHasta: '2026-12-31',
    fechaPublicacion: '2026-06-08',
    inmobiliaria: { nombre: 'Paraná Propiedades', telefono: '595981456789' },
  },
  {
    id: 'c3d4',
    slug: 'departamento-en-venta-carmelitas-asuncion-c3d4',
    operacion: 'venta',
    tipo: 'departamento',
    titulo: 'Departamento de categoría en Carmelitas',
    descripcion:
      'Exclusivo departamento en torre premium sobre Avenida San Martín, en zona Carmelitas. Living comedor con balcón aterrazado y vista abierta, cocina equipada y suite principal con vestidor. El edificio ofrece piscina, gimnasio y seguridad las 24 horas.',
    precioUSD: 245000,
    barrio: 'Carmelitas',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 165,
    superficieTerreno: 0,
    caracteristicas: [
      'Piscina',
      'Gimnasio',
      'Aire acondicionado',
      'Seguridad 24hs',
      'Balcón',
      'Ascensor',
    ],
    coordenadas: { lat: -25.2719, lng: -57.5712 },
    imagenes: [
      'prop2-1.jpg',
      'prop2-2.jpg',
      'prop2-3.jpg',
      'prop2-4.jpg',
      'prop2-5.jpg',
      'prop2-6.jpg',
      'prop2-7.jpg',
      'prop2-8.jpg',
    ],
    destacada: true,
    destacadaHasta: '2026-10-31',
    fechaPublicacion: '2026-06-05',
    inmobiliaria: { nombre: 'Asunción Realty', telefono: '595971234567' },
  },
  {
    id: 'e5f6',
    slug: 'casa-familiar-en-venta-lambare-e5f6',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa familiar con amplio jardín en Lambaré',
    descripcion:
      'Cómoda casa de dos plantas en barrio residencial de Lambaré, a pocos minutos de Asunción. Tres dormitorios, living luminoso y un fondo verde con espacio para piscina. Excelente opción para una familia que busca tranquilidad sin alejarse de la ciudad.',
    precioUSD: 175000,
    barrio: 'San Pedro',
    ciudad: 'Lambaré',
    departamento: 'Central',
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 210,
    superficieTerreno: 360,
    caracteristicas: ['Jardín', 'Quincho', 'Aire acondicionado', 'Parrilla'],
    coordenadas: { lat: -25.3461, lng: -57.6149 },
    imagenes: [
      'prop3-1.jpg',
      'prop3-2.jpg',
      'prop3-3.jpg',
      'prop3-4.jpg',
      'prop3-5.jpg',
      'prop3-6.jpg',
      'prop3-7.jpg',
      'prop3-8.jpg',
    ],
    destacada: true,
    destacadaHasta: null,
    fechaPublicacion: '2026-06-02',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'g7h8',
    slug: 'duplex-en-venta-san-lorenzo-g7h8',
    operacion: 'venta',
    tipo: 'duplex',
    titulo: 'Dúplex a estrenar en San Lorenzo',
    descripcion:
      'Moderno dúplex de construcción reciente en un complejo cerrado de San Lorenzo. Planta baja con ambientes integrados y patio, planta alta con dos suites. Terminaciones actuales y bajo gasto de mantenimiento, listo para habitar.',
    precioUSD: 138000,
    barrio: 'Villa Universitaria',
    ciudad: 'San Lorenzo',
    departamento: 'Central',
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 160,
    superficieTerreno: 200,
    caracteristicas: [
      'A estrenar',
      'Patio',
      'Aire acondicionado',
      'Seguridad 24hs',
      'Cocina equipada',
    ],
    coordenadas: { lat: -25.3389, lng: -57.5089 },
    imagenes: [
      'prop4-1.jpg',
      'prop4-2.jpg',
      'prop4-3.jpg',
      'prop4-4.jpg',
      'prop4-5.jpg',
      'prop4-6.jpg',
      'prop4-7.jpg',
      'prop4-8.jpg',
    ],
    destacada: true,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-28',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'i9j0',
    slug: 'departamento-en-alquiler-recoleta-asuncion-i9j0',
    operacion: 'alquiler',
    tipo: 'departamento',
    titulo: 'Departamento amoblado en alquiler en Recoleta',
    descripcion:
      'Luminoso departamento de dos dormitorios totalmente amoblado, en una de las mejores zonas de Asunción. Listo para mudarse, con cocina equipada, aire acondicionado en todos los ambientes y cochera. Ideal para profesionales o pareja.',
    precioUSD: 950,
    barrio: 'Recoleta',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 95,
    superficieTerreno: 0,
    caracteristicas: [
      'Amoblado',
      'Aire acondicionado',
      'Seguridad 24hs',
      'Ascensor',
      'Balcón',
    ],
    coordenadas: { lat: -25.2897, lng: -57.5736 },
    imagenes: [
      'prop5-1.jpg',
      'prop5-2.jpg',
      'prop5-3.jpg',
      'prop5-4.jpg',
      'prop5-5.jpg',
      'prop5-6.jpg',
      'prop5-7.jpg',
      'prop5-8.jpg',
    ],
    destacada: true,
    destacadaHasta: '2026-09-30',
    fechaPublicacion: '2026-06-10',
    inmobiliaria: { nombre: 'Asunción Realty', telefono: '595971234567' },
  },
  {
    id: 'k1l2',
    slug: 'terreno-en-venta-luque-k1l2',
    operacion: 'venta',
    tipo: 'terreno',
    titulo: 'Terreno en zona de alto crecimiento en Luque',
    descripcion:
      'Excelente terreno en esquina sobre calle asfaltada, en una zona de Luque con fuerte desarrollo inmobiliario. Todos los servicios disponibles y rápido acceso a la Avenida Aviadores del Chaco. Ideal para vivienda o inversión.',
    precioUSD: 78000,
    barrio: 'Mora Cué',
    ciudad: 'Luque',
    departamento: 'Central',
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 480,
    caracteristicas: ['Esquina', 'Asfaltado', 'Todos los servicios'],
    coordenadas: { lat: -25.2701, lng: -57.4889 },
    imagenes: [
      'prop6-1.jpg',
      'prop6-2.jpg',
      'prop6-3.jpg',
      'prop6-4.jpg',
      'prop6-5.jpg',
      'prop6-6.jpg',
      'prop6-7.jpg',
      'prop6-8.jpg',
    ],
    destacada: true,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-30',
    inmobiliaria: { nombre: 'Inversiones del Este', telefono: '595983456789' },
  },

  // ───────────────────────────────────────── Rest (destacada: false) ───────
  {
    id: 'm3n4',
    slug: 'casa-en-venta-las-mercedes-asuncion-m3n4',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa con estilo en Las Mercedes',
    descripcion:
      'Encantadora casa de una planta en el tradicional barrio Las Mercedes, con detalles de buen gusto y mantenimiento impecable. Patio interno con vegetación y galería techada. A metros de avenidas principales y comercios.',
    precioUSD: 320000,
    barrio: 'Las Mercedes',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 4,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 280,
    superficieTerreno: 450,
    caracteristicas: ['Jardín', 'Galería', 'Aire acondicionado', 'Dependencia de servicio'],
    coordenadas: { lat: -25.2884, lng: -57.5829 },
    imagenes: ['prop1-1.jpg', 'prop1-2.jpg', 'prop1-8.jpg', 'prop3-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-20',
    inmobiliaria: { nombre: 'Paraná Propiedades', telefono: '595981456789' },
  },
  {
    id: 'o5p6',
    slug: 'departamento-en-venta-mburucuya-asuncion-o5p6',
    operacion: 'venta',
    tipo: 'departamento',
    titulo: 'Departamento de 2 dormitorios en Mburucuyá',
    descripcion:
      'Departamento bien distribuido en edificio moderno de Mburucuyá, con amenities y seguridad. Cocina integrada al living y balcón con vista despejada. Buena relación precio-ubicación para primera vivienda o renta.',
    precioUSD: 118000,
    barrio: 'Mburucuyá',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 88,
    superficieTerreno: 0,
    caracteristicas: ['Piscina', 'Gimnasio', 'Seguridad 24hs', 'Ascensor', 'Balcón'],
    coordenadas: { lat: -25.3099, lng: -57.5521 },
    imagenes: ['prop2-1.jpg', 'prop2-3.jpg', 'prop2-5.jpg', 'prop5-2.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-18',
    inmobiliaria: { nombre: 'Asunción Realty', telefono: '595971234567' },
  },
  {
    id: 'q7r8',
    slug: 'casa-en-venta-manora-asuncion-q7r8',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa premium en barrio cerrado de Manorá',
    descripcion:
      'Espectacular residencia en uno de los barrios cerrados más exclusivos de Asunción. Diseño de autor, doble altura en el living, piscina con deck y home theater. Seguridad perimetral y áreas comunes de primer nivel.',
    precioUSD: 620000,
    barrio: 'Manorá',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 5,
    banos: 5,
    cocheras: 4,
    superficieConstruida: 540,
    superficieTerreno: 720,
    caracteristicas: [
      'Piscina',
      'Quincho',
      'Home theater',
      'Seguridad 24hs',
      'Barrio cerrado',
      'Aire acondicionado',
    ],
    coordenadas: { lat: -25.3012, lng: -57.5498 },
    imagenes: ['prop1-1.jpg', 'prop1-2.jpg', 'prop1-4.jpg', 'prop1-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-15',
    inmobiliaria: { nombre: 'Premium Estates Paraguay', telefono: '595984567890' },
  },
  {
    id: 's9t0',
    slug: 'departamento-en-alquiler-villa-morra-asuncion-s9t0',
    operacion: 'alquiler',
    tipo: 'departamento',
    titulo: 'Monoambiente moderno en alquiler en Villa Morra',
    descripcion:
      'Práctico monoambiente en torre nueva de Villa Morra, ideal para estudiantes o profesionales. Totalmente equipado, con amenities completos y excelente ubicación a pasos del Shopping del Sol. Gastos comunes accesibles.',
    precioUSD: 480,
    barrio: 'Villa Morra',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 1,
    banos: 1,
    cocheras: 1,
    superficieConstruida: 45,
    superficieTerreno: 0,
    caracteristicas: ['Amoblado', 'Piscina', 'Gimnasio', 'Seguridad 24hs', 'Ascensor'],
    coordenadas: { lat: -25.2951, lng: -57.5762 },
    imagenes: ['prop5-1.jpg', 'prop5-3.jpg', 'prop2-2.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-06-09',
    inmobiliaria: { nombre: 'Asunción Realty', telefono: '595971234567' },
  },
  {
    id: 'u1v2',
    slug: 'casa-en-alquiler-lambare-u1v2',
    operacion: 'alquiler',
    tipo: 'casa',
    titulo: 'Casa en alquiler con patio en Lambaré',
    descripcion:
      'Casa de tres dormitorios en alquiler, en zona residencial y tranquila de Lambaré. Cuenta con patio amplio, parrilla y cochera para dos vehículos. Disponible para contrato familiar de largo plazo.',
    precioUSD: 720,
    barrio: 'Santa Ana',
    ciudad: 'Lambaré',
    departamento: 'Central',
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 180,
    superficieTerreno: 300,
    caracteristicas: ['Patio', 'Parrilla', 'Aire acondicionado'],
    coordenadas: { lat: -25.3502, lng: -57.6201 },
    imagenes: ['prop3-1.jpg', 'prop3-2.jpg', 'prop3-7.jpg', 'prop1-8.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-06-01',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'w3x4',
    slug: 'casa-en-alquiler-san-lorenzo-w3x4',
    operacion: 'alquiler',
    tipo: 'casa',
    titulo: 'Casa amplia en alquiler en San Lorenzo',
    descripcion:
      'Espaciosa casa para alquiler en San Lorenzo, cerca de la Universidad Nacional. Cuatro dormitorios, dos baños y un gran fondo verde. Ideal para familia numerosa o uso compartido por estudiantes.',
    precioUSD: 650,
    barrio: 'Centro',
    ciudad: 'San Lorenzo',
    departamento: 'Central',
    dormitorios: 4,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 220,
    superficieTerreno: 400,
    caracteristicas: ['Jardín', 'Parrilla', 'Dependencia de servicio'],
    coordenadas: { lat: -25.3401, lng: -57.5081 },
    imagenes: ['prop3-1.jpg', 'prop3-3.jpg', 'prop3-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-25',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'y5z6',
    slug: 'oficina-en-venta-villa-morra-asuncion-y5z6',
    operacion: 'venta',
    tipo: 'oficina',
    titulo: 'Oficina corporativa en torre de Villa Morra',
    descripcion:
      'Oficina en piso alto de torre corporativa sobre Avenida Mariscal López, en plena zona de negocios. Planta libre lista para distribuir, con dos cocheras y recepción del edificio. Excelente inversión de renta.',
    precioUSD: 185000,
    barrio: 'Villa Morra',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 0,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 120,
    superficieTerreno: 0,
    caracteristicas: ['Aire acondicionado', 'Seguridad 24hs', 'Ascensor', 'Planta libre'],
    coordenadas: { lat: -25.2967, lng: -57.5739 },
    imagenes: ['prop2-1.jpg', 'prop2-4.jpg', 'prop2-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-12',
    inmobiliaria: { nombre: 'Premium Estates Paraguay', telefono: '595984567890' },
  },
  {
    id: 'a7b8',
    slug: 'local-comercial-en-alquiler-asuncion-a7b8',
    operacion: 'alquiler',
    tipo: 'local',
    titulo: 'Local comercial sobre avenida en Asunción',
    descripcion:
      'Local comercial a la calle con gran vidriera, sobre avenida de alto tránsito en el microcentro. Salón amplio, depósito y baño. Excelente exposición para comercio, showroom o gastronomía.',
    precioUSD: 1500,
    barrio: 'Centro',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 0,
    banos: 1,
    cocheras: 0,
    superficieConstruida: 110,
    superficieTerreno: 0,
    caracteristicas: ['A la calle', 'Vidriera', 'Depósito'],
    coordenadas: { lat: -25.2841, lng: -57.6342 },
    imagenes: ['prop2-3.jpg', 'prop5-6.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-22',
    inmobiliaria: { nombre: 'Asunción Realty', telefono: '595971234567' },
  },
  {
    id: 'c9d0',
    slug: 'terreno-en-venta-mariano-roque-alonso-c9d0',
    operacion: 'venta',
    tipo: 'terreno',
    titulo: 'Terreno amplio en Mariano Roque Alonso',
    descripcion:
      'Generoso terreno en zona en expansión de Mariano Roque Alonso, con frente a calle empedrada. Apto para vivienda unifamiliar o pequeño emprendimiento. A minutos del acceso a la Ruta Transchaco.',
    precioUSD: 62000,
    barrio: 'San Roque',
    ciudad: 'Mariano Roque Alonso',
    departamento: 'Central',
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 540,
    caracteristicas: ['Empedrado', 'Agua corriente', 'Energía eléctrica'],
    coordenadas: { lat: -25.2012, lng: -57.5321 },
    imagenes: ['prop6-1.jpg', 'prop6-3.jpg', 'prop6-5.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-10',
    inmobiliaria: { nombre: 'Inversiones del Este', telefono: '595983456789' },
  },
  {
    id: 'e1f2',
    slug: 'casa-en-venta-fernando-de-la-mora-e1f2',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa de tres dormitorios en Fernando de la Mora',
    descripcion:
      'Sólida casa de material en Fernando de la Mora, zona sur, con buena distribución y patio trasero. Ambientes frescos, cochera techada y depósito. Lista para habitar, en calle tranquila y bien conectada.',
    precioUSD: 132000,
    barrio: 'Zona Sur',
    ciudad: 'Fernando de la Mora',
    departamento: 'Central',
    dormitorios: 3,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 165,
    superficieTerreno: 288,
    caracteristicas: ['Patio', 'Cochera techada', 'Depósito'],
    coordenadas: { lat: -25.3231, lng: -57.5389 },
    imagenes: ['prop3-1.jpg', 'prop3-4.jpg', 'prop3-6.jpg', 'prop3-8.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-08',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'g3h4',
    slug: 'departamento-en-venta-las-mercedes-asuncion-g3h4',
    operacion: 'venta',
    tipo: 'departamento',
    titulo: 'Departamento luminoso en Las Mercedes',
    descripcion:
      'Departamento de tres dormitorios en edificio consolidado de Las Mercedes, con excelente iluminación natural. Living comedor amplio, cocina independiente y dos cocheras. Zona céntrica y muy bien servida.',
    precioUSD: 158000,
    barrio: 'Las Mercedes',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 128,
    superficieTerreno: 0,
    caracteristicas: ['Aire acondicionado', 'Seguridad 24hs', 'Ascensor', 'Balcón'],
    coordenadas: { lat: -25.2872, lng: -57.5851 },
    imagenes: ['prop2-1.jpg', 'prop2-2.jpg', 'prop2-6.jpg', 'prop5-4.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-06',
    inmobiliaria: { nombre: 'Paraná Propiedades', telefono: '595981456789' },
  },
  {
    id: 'i5j6',
    slug: 'duplex-en-venta-luque-i5j6',
    operacion: 'venta',
    tipo: 'duplex',
    titulo: 'Dúplex en condominio cerrado en Luque',
    descripcion:
      'Dúplex en condominio con seguridad y área de esparcimiento, en zona residencial de Luque. Tres dormitorios, patio propio y cochera. Construcción de calidad y bajos gastos comunes.',
    precioUSD: 112000,
    barrio: 'Laurelty',
    ciudad: 'Luque',
    departamento: 'Central',
    dormitorios: 3,
    banos: 3,
    cocheras: 1,
    superficieConstruida: 145,
    superficieTerreno: 180,
    caracteristicas: ['Patio', 'Seguridad 24hs', 'Barrio cerrado', 'Aire acondicionado'],
    coordenadas: { lat: -25.2689, lng: -57.4912 },
    imagenes: ['prop4-1.jpg', 'prop4-2.jpg', 'prop4-5.jpg', 'prop4-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-04',
    inmobiliaria: { nombre: 'Inversiones del Este', telefono: '595983456789' },
  },
  {
    id: 'k7l8',
    slug: 'casa-en-venta-capiata-k7l8',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa económica con terreno en Capiatá',
    descripcion:
      'Casa de dos dormitorios sobre amplio terreno en Capiatá, con lugar de sobra para ampliar o construir piscina. Excelente oportunidad de primera vivienda a buen precio, cerca de la Ruta Mariscal Estigarribia.',
    precioUSD: 68000,
    barrio: 'San Antonio',
    ciudad: 'Capiatá',
    departamento: 'Central',
    dormitorios: 2,
    banos: 1,
    cocheras: 2,
    superficieConstruida: 95,
    superficieTerreno: 450,
    caracteristicas: ['Jardín', 'Pozo artesiano', 'Parrilla'],
    coordenadas: { lat: -25.3551, lng: -57.4221 },
    imagenes: ['prop3-1.jpg', 'prop3-7.jpg', 'prop3-5.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-02',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'm9n0',
    slug: 'departamento-en-venta-recoleta-asuncion-m9n0',
    operacion: 'venta',
    tipo: 'departamento',
    titulo: 'Departamento con vista en Recoleta',
    descripcion:
      'Elegante departamento en piso alto con vista panorámica a la ciudad, en zona Recoleta. Suite principal con vestidor, cocina equipada y amplio balcón aterrazado. Edificio con piscina infinity y gimnasio.',
    precioUSD: 295000,
    barrio: 'Recoleta',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 178,
    superficieTerreno: 0,
    caracteristicas: [
      'Piscina',
      'Gimnasio',
      'Aire acondicionado',
      'Seguridad 24hs',
      'Balcón',
      'Vista panorámica',
    ],
    coordenadas: { lat: -25.2909, lng: -57.5701 },
    imagenes: ['prop2-1.jpg', 'prop2-2.jpg', 'prop2-4.jpg', 'prop5-1.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-29',
    inmobiliaria: { nombre: 'Premium Estates Paraguay', telefono: '595984567890' },
  },
  {
    id: 'o1p2',
    slug: 'casa-en-venta-ykua-sati-asuncion-o1p2',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa con jardín en Ykua Satí',
    descripcion:
      'Bonita casa de una planta en el residencial barrio Ykua Satí, con jardín frontal y galería. Tres dormitorios, living comedor integrado y cochera doble. Entorno tranquilo y arbolado.',
    precioUSD: 268000,
    barrio: 'Ykua Satí',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 245,
    superficieTerreno: 420,
    caracteristicas: ['Jardín', 'Galería', 'Aire acondicionado', 'Quincho'],
    coordenadas: { lat: -25.3041, lng: -57.5689 },
    imagenes: ['prop1-1.jpg', 'prop1-3.jpg', 'prop1-7.jpg', 'prop1-8.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-27',
    inmobiliaria: { nombre: 'Paraná Propiedades', telefono: '595981456789' },
  },
  {
    id: 'q3r4',
    slug: 'departamento-en-alquiler-carmelitas-asuncion-q3r4',
    operacion: 'alquiler',
    tipo: 'departamento',
    titulo: 'Departamento de 1 dormitorio en alquiler en Carmelitas',
    descripcion:
      'Moderno departamento de un dormitorio en Carmelitas, con balcón y amenities completos. Ambientes funcionales, cocina equipada y cochera. Ideal para profesional joven en una de las mejores zonas de la ciudad.',
    precioUSD: 620,
    barrio: 'Carmelitas',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 1,
    banos: 1,
    cocheras: 1,
    superficieConstruida: 58,
    superficieTerreno: 0,
    caracteristicas: ['Piscina', 'Gimnasio', 'Seguridad 24hs', 'Ascensor', 'Balcón'],
    coordenadas: { lat: -25.2731, lng: -57.5698 },
    imagenes: ['prop5-1.jpg', 'prop5-2.jpg', 'prop2-5.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-06-07',
    inmobiliaria: { nombre: 'Asunción Realty', telefono: '595971234567' },
  },
  {
    id: 's5t6',
    slug: 'casa-en-venta-jara-asuncion-s5t6',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa antigua con potencial en Jara',
    descripcion:
      'Casa de estilo tradicional en el barrio Jara, sobre lote amplio con árboles añosos. Ideal para reciclar o desarrollar, conservando su carácter. Ubicación céntrica y de gran demanda.',
    precioUSD: 215000,
    barrio: 'Jara',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 4,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 230,
    superficieTerreno: 500,
    caracteristicas: ['Jardín', 'A refaccionar', 'Galería'],
    coordenadas: { lat: -25.3001, lng: -57.6101 },
    imagenes: ['prop3-1.jpg', 'prop3-2.jpg', 'prop1-8.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-24',
    inmobiliaria: { nombre: 'Paraná Propiedades', telefono: '595981456789' },
  },
  {
    id: 'u7v8',
    slug: 'terreno-en-venta-san-lorenzo-u7v8',
    operacion: 'venta',
    tipo: 'terreno',
    titulo: 'Terreno en zona comercial de San Lorenzo',
    descripcion:
      'Terreno con excelente frente sobre avenida comercial en San Lorenzo, apto para emprendimiento o edificio. Todos los servicios y altísima visibilidad. Oportunidad de inversión en zona consolidada.',
    precioUSD: 145000,
    barrio: 'Centro',
    ciudad: 'San Lorenzo',
    departamento: 'Central',
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 600,
    caracteristicas: ['Esquina', 'Asfaltado', 'Zona comercial', 'Todos los servicios'],
    coordenadas: { lat: -25.3372, lng: -57.5102 },
    imagenes: ['prop6-1.jpg', 'prop6-2.jpg', 'prop6-4.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-21',
    inmobiliaria: { nombre: 'Inversiones del Este', telefono: '595983456789' },
  },
  {
    id: 'w9x0',
    slug: 'departamento-en-venta-villa-morra-asuncion-w9x0',
    operacion: 'venta',
    tipo: 'departamento',
    titulo: 'Departamento a estrenar en Villa Morra',
    descripcion:
      'Departamento a estrenar en torre boutique de Villa Morra, con terminaciones premium y domótica. Dos suites, living amplio y balcón con parrilla. Amenities de lujo y ubicación inmejorable.',
    precioUSD: 210000,
    barrio: 'Villa Morra',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 2,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 132,
    superficieTerreno: 0,
    caracteristicas: [
      'A estrenar',
      'Piscina',
      'Gimnasio',
      'Seguridad 24hs',
      'Balcón',
      'Domótica',
    ],
    coordenadas: { lat: -25.2941, lng: -57.5771 },
    imagenes: ['prop2-1.jpg', 'prop2-2.jpg', 'prop2-3.jpg', 'prop2-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-06-03',
    inmobiliaria: { nombre: 'Premium Estates Paraguay', telefono: '595984567890' },
  },
  {
    id: 'y1z2',
    slug: 'casa-en-venta-encarnacion-y1z2',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa frente a la costanera en Encarnación',
    descripcion:
      'Hermosa casa moderna a pocas cuadras de la costanera de Encarnación, con vista al río Paraná en las cercanías. Tres dormitorios, piscina y galería con quincho. Perfecta para vivir o como casa de veraneo.',
    precioUSD: 235000,
    barrio: 'San Roque',
    ciudad: 'Encarnación',
    departamento: 'Itapúa',
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 220,
    superficieTerreno: 400,
    caracteristicas: ['Piscina', 'Quincho', 'Galería', 'Aire acondicionado'],
    coordenadas: { lat: -27.3309, lng: -55.8663 },
    imagenes: ['prop1-1.jpg', 'prop1-2.jpg', 'prop1-7.jpg', 'prop3-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-18',
    inmobiliaria: { nombre: 'Sur Inmobiliaria', telefono: '595985678901' },
  },
  {
    id: 'a3b4',
    slug: 'departamento-en-alquiler-encarnacion-a3b4',
    operacion: 'alquiler',
    tipo: 'departamento',
    titulo: 'Departamento con vista al río en Encarnación',
    descripcion:
      'Departamento de dos dormitorios en alquiler, con balcón y vista parcial al río en Encarnación. Edificio nuevo con seguridad y cochera. Ideal para quienes buscan calidad de vida frente a la Perla del Sur.',
    precioUSD: 540,
    barrio: 'Centro',
    ciudad: 'Encarnación',
    departamento: 'Itapúa',
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 82,
    superficieTerreno: 0,
    caracteristicas: ['Aire acondicionado', 'Seguridad 24hs', 'Ascensor', 'Balcón'],
    coordenadas: { lat: -27.3331, lng: -55.8701 },
    imagenes: ['prop5-1.jpg', 'prop5-4.jpg', 'prop2-2.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-06-04',
    inmobiliaria: { nombre: 'Sur Inmobiliaria', telefono: '595985678901' },
  },
  {
    id: 'c5d6',
    slug: 'casa-en-venta-ciudad-del-este-c5d6',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa moderna en barrio residencial de Ciudad del Este',
    descripcion:
      'Casa de diseño actual en zona residencial de Ciudad del Este, cerca del km 7. Cuatro dormitorios, piscina y amplio quincho techado. Construcción sólida y excelente conectividad con el centro.',
    precioUSD: 198000,
    barrio: 'Km 7',
    ciudad: 'Ciudad del Este',
    departamento: 'Alto Paraná',
    dormitorios: 4,
    banos: 3,
    cocheras: 3,
    superficieConstruida: 300,
    superficieTerreno: 500,
    caracteristicas: ['Piscina', 'Quincho', 'Aire acondicionado', 'Seguridad 24hs'],
    coordenadas: { lat: -25.5097, lng: -54.6112 },
    imagenes: ['prop1-1.jpg', 'prop1-4.jpg', 'prop1-7.jpg', 'prop3-1.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-15',
    inmobiliaria: { nombre: 'Este Negocios Inmobiliarios', telefono: '595986789012' },
  },
  {
    id: 'e7f8',
    slug: 'terreno-en-venta-ciudad-del-este-e7f8',
    operacion: 'venta',
    tipo: 'terreno',
    titulo: 'Terreno para inversión en Ciudad del Este',
    descripcion:
      'Amplio terreno en zona de crecimiento de Ciudad del Este, ideal para desarrollo comercial o residencial. Buen frente y fácil acceso. Documentación al día, listo para escriturar.',
    precioUSD: 95000,
    barrio: 'Área 1',
    ciudad: 'Ciudad del Este',
    departamento: 'Alto Paraná',
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 800,
    caracteristicas: ['Asfaltado', 'Todos los servicios', 'Apto comercial'],
    coordenadas: { lat: -25.5151, lng: -54.6201 },
    imagenes: ['prop6-1.jpg', 'prop6-3.jpg', 'prop6-6.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-12',
    inmobiliaria: { nombre: 'Este Negocios Inmobiliarios', telefono: '595986789012' },
  },
  {
    id: 'g9h0',
    slug: 'oficina-en-alquiler-asuncion-g9h0',
    operacion: 'alquiler',
    tipo: 'oficina',
    titulo: 'Oficina equipada en alquiler en el centro',
    descripcion:
      'Oficina lista para usar en edificio corporativo del microcentro asunceno. Ambientes divididos, sala de reuniones y kitchenette. Incluye cochera y acceso a fibra óptica. Disponible de inmediato.',
    precioUSD: 850,
    barrio: 'Centro',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 0,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 90,
    superficieTerreno: 0,
    caracteristicas: ['Aire acondicionado', 'Seguridad 24hs', 'Ascensor', 'Fibra óptica'],
    coordenadas: { lat: -25.2851, lng: -57.6371 },
    imagenes: ['prop2-4.jpg', 'prop2-7.jpg', 'prop5-6.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-19',
    inmobiliaria: { nombre: 'Asunción Realty', telefono: '595971234567' },
  },
  {
    id: 'i1j2',
    slug: 'local-en-venta-san-lorenzo-i1j2',
    operacion: 'venta',
    tipo: 'local',
    titulo: 'Local comercial en venta sobre avenida en San Lorenzo',
    descripcion:
      'Local a la calle con buena superficie sobre avenida transitada de San Lorenzo. Salón principal, entrepiso y baño. Ideal para inversión con renta asegurada o negocio propio.',
    precioUSD: 128000,
    barrio: 'Centro',
    ciudad: 'San Lorenzo',
    departamento: 'Central',
    dormitorios: 0,
    banos: 1,
    cocheras: 1,
    superficieConstruida: 140,
    superficieTerreno: 160,
    caracteristicas: ['A la calle', 'Entrepiso', 'Zona comercial'],
    coordenadas: { lat: -25.3389, lng: -57.5121 },
    imagenes: ['prop2-3.jpg', 'prop6-2.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-09',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'k3l4',
    slug: 'casa-en-venta-luque-k3l4',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa con piscina en barrio cerrado de Luque',
    descripcion:
      'Confortable casa en barrio cerrado de Luque, con seguridad 24 horas y áreas verdes comunes. Tres dormitorios en suite, piscina propia y quincho. Entorno seguro ideal para familias.',
    precioUSD: 245000,
    barrio: 'Isla Bogado',
    ciudad: 'Luque',
    departamento: 'Central',
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 260,
    superficieTerreno: 380,
    caracteristicas: [
      'Piscina',
      'Quincho',
      'Barrio cerrado',
      'Seguridad 24hs',
      'Aire acondicionado',
    ],
    coordenadas: { lat: -25.2741, lng: -57.4831 },
    imagenes: ['prop1-1.jpg', 'prop1-2.jpg', 'prop1-7.jpg', 'prop4-3.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-26',
    inmobiliaria: { nombre: 'Inversiones del Este', telefono: '595983456789' },
  },
  {
    id: 'm5n6',
    slug: 'departamento-en-venta-san-lorenzo-m5n6',
    operacion: 'venta',
    tipo: 'departamento',
    titulo: 'Departamento accesible en San Lorenzo',
    descripcion:
      'Departamento de dos dormitorios en edificio tranquilo de San Lorenzo, próximo a comercios y transporte. Buena distribución, cocina independiente y cochera. Excelente entrada al mercado inmobiliario.',
    precioUSD: 84000,
    barrio: 'Centro',
    ciudad: 'San Lorenzo',
    departamento: 'Central',
    dormitorios: 2,
    banos: 1,
    cocheras: 1,
    superficieConstruida: 72,
    superficieTerreno: 0,
    caracteristicas: ['Ascensor', 'Seguridad 24hs', 'Balcón'],
    coordenadas: { lat: -25.3411, lng: -57.5061 },
    imagenes: ['prop5-2.jpg', 'prop2-5.jpg', 'prop2-6.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-06',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'o7p8',
    slug: 'casa-en-alquiler-villa-morra-asuncion-o7p8',
    operacion: 'alquiler',
    tipo: 'casa',
    titulo: 'Casa para oficina o vivienda en Villa Morra',
    descripcion:
      'Versátil casa en Villa Morra, apta para vivienda familiar o uso comercial/profesional. Amplios ambientes, estacionamiento para varios vehículos y excelente ubicación sobre calle de buen tránsito.',
    precioUSD: 1800,
    barrio: 'Villa Morra',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 4,
    banos: 3,
    cocheras: 3,
    superficieConstruida: 320,
    superficieTerreno: 480,
    caracteristicas: ['Jardín', 'Apto profesional', 'Aire acondicionado', 'Dependencia de servicio'],
    coordenadas: { lat: -25.2922, lng: -57.5751 },
    imagenes: ['prop1-1.jpg', 'prop1-2.jpg', 'prop1-5.jpg', 'prop1-8.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-29',
    inmobiliaria: { nombre: 'Premium Estates Paraguay', telefono: '595984567890' },
  },
  {
    id: 'q9r0',
    slug: 'terreno-en-venta-capiata-q9r0',
    operacion: 'venta',
    tipo: 'terreno',
    titulo: 'Terreno residencial en Capiatá',
    descripcion:
      'Terreno plano en loteamiento residencial de Capiatá, con calles internas y servicios. Ideal para construir tu primera vivienda con facilidades. A pocos minutos de la ruta principal.',
    precioUSD: 38000,
    barrio: 'Villa Carmelo',
    ciudad: 'Capiatá',
    departamento: 'Central',
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 360,
    caracteristicas: ['Loteamiento', 'Energía eléctrica', 'Agua corriente'],
    coordenadas: { lat: -25.3571, lng: -57.4261 },
    imagenes: ['prop6-1.jpg', 'prop6-5.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-04-03',
    inmobiliaria: { nombre: 'Inversiones del Este', telefono: '595983456789' },
  },
  {
    id: 's1t2',
    slug: 'departamento-en-venta-mariano-roque-alonso-s1t2',
    operacion: 'venta',
    tipo: 'departamento',
    titulo: 'Departamento nuevo en Mariano Roque Alonso',
    descripcion:
      'Departamento de dos dormitorios en edificio reciente de Mariano Roque Alonso, con amenities y seguridad. Cocina equipada, balcón y cochera. Zona en desarrollo con buena plusvalía.',
    precioUSD: 96000,
    barrio: 'Centro',
    ciudad: 'Mariano Roque Alonso',
    departamento: 'Central',
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 78,
    superficieTerreno: 0,
    caracteristicas: ['Piscina', 'Seguridad 24hs', 'Ascensor', 'Balcón'],
    coordenadas: { lat: -25.1981, lng: -57.5351 },
    imagenes: ['prop2-1.jpg', 'prop2-5.jpg', 'prop5-1.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-16',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'u3v4',
    slug: 'casa-en-venta-carmelitas-asuncion-u3v4',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa señorial en Carmelitas',
    descripcion:
      'Imponente residencia en el prestigioso barrio Carmelitas, sobre lote esquina. Ambientes amplios y luminosos, piscina, quincho y dependencia completa. Una propiedad para disfrutar en familia por años.',
    precioUSD: 540000,
    barrio: 'Carmelitas',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 5,
    banos: 4,
    cocheras: 4,
    superficieConstruida: 480,
    superficieTerreno: 700,
    caracteristicas: [
      'Piscina',
      'Quincho',
      'Esquina',
      'Seguridad 24hs',
      'Aire acondicionado',
      'Dependencia de servicio',
    ],
    coordenadas: { lat: -25.2701, lng: -57.5681 },
    imagenes: ['prop1-1.jpg', 'prop1-2.jpg', 'prop1-4.jpg', 'prop1-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-23',
    inmobiliaria: { nombre: 'Premium Estates Paraguay', telefono: '595984567890' },
  },
  {
    id: 'w5x6',
    slug: 'departamento-en-venta-fernando-de-la-mora-w5x6',
    operacion: 'venta',
    tipo: 'departamento',
    titulo: 'Departamento familiar en Fernando de la Mora',
    descripcion:
      'Amplio departamento de tres dormitorios en Fernando de la Mora, zona norte. Living comedor espacioso, lavadero independiente y dos cocheras. Edificio tranquilo con buena administración.',
    precioUSD: 105000,
    barrio: 'Zona Norte',
    ciudad: 'Fernando de la Mora',
    departamento: 'Central',
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 110,
    superficieTerreno: 0,
    caracteristicas: ['Ascensor', 'Seguridad 24hs', 'Lavadero', 'Balcón'],
    coordenadas: { lat: -25.3121, lng: -57.5341 },
    imagenes: ['prop2-2.jpg', 'prop2-6.jpg', 'prop5-4.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-03-30',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'y7z8',
    slug: 'duplex-en-alquiler-lambare-y7z8',
    operacion: 'alquiler',
    tipo: 'duplex',
    titulo: 'Dúplex en alquiler en Lambaré',
    descripcion:
      'Dúplex de dos dormitorios en alquiler, en complejo con seguridad en Lambaré. Patio propio, cochera y ambientes bien ventilados. Disponible para contrato de largo plazo, ideal para parejas o familias pequeñas.',
    precioUSD: 580,
    barrio: 'Las Mercedes',
    ciudad: 'Lambaré',
    departamento: 'Central',
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 110,
    superficieTerreno: 130,
    caracteristicas: ['Patio', 'Seguridad 24hs', 'Aire acondicionado'],
    coordenadas: { lat: -25.3531, lng: -57.6131 },
    imagenes: ['prop4-1.jpg', 'prop4-2.jpg', 'prop4-6.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-31',
    inmobiliaria: { nombre: 'Central Hogar', telefono: '595982345678' },
  },
  {
    id: 'a9b0',
    slug: 'casa-en-venta-mburucuya-asuncion-a9b0',
    operacion: 'venta',
    tipo: 'casa',
    titulo: 'Casa con quincho y piscina en Mburucuyá',
    descripcion:
      'Acogedora casa de dos plantas en Mburucuyá, con un fondo pensado para el disfrute: piscina, quincho con parrilla y jardín. Tres dormitorios en planta alta y ambientes sociales integrados abajo.',
    precioUSD: 285000,
    barrio: 'Mburucuyá',
    ciudad: 'Asunción',
    departamento: 'Capital',
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 270,
    superficieTerreno: 400,
    caracteristicas: ['Piscina', 'Quincho', 'Parrilla', 'Jardín', 'Aire acondicionado'],
    coordenadas: { lat: -25.3081, lng: -57.5541 },
    imagenes: ['prop1-1.jpg', 'prop1-3.jpg', 'prop1-7.jpg', 'prop3-7.jpg'],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: '2026-05-14',
    inmobiliaria: { nombre: 'Paraná Propiedades', telefono: '595981456789' },
  },
];

/** Final, validated-shape seed with `precioGs` derived from `precioUSD`. */
export const listingsSeed: Listing[] = seed.map((l) => ({
  ...l,
  precioGs: Math.round(l.precioUSD * FX_PYG_USD),
}));
