import type { Listing } from "@/lib/listings-schema";

/**
 * SEED DATA — Phase 1 source of truth.
 *
 * This file is read ONLY by lib/listings-repo.ts. No page, API route, sitemap
 * or component may import it directly (that's the data-source seam). In Phase 2
 * the repo's function bodies are swapped to query Supabase and this file goes
 * away — pages and the API never notice.
 *
 * To add a listing: copy a block in `raw` below, fill every field, and save.
 * `precioGs` is derived automatically (precioUSD * 7300), so you only set USD.
 * See README §"How to add a new listing" for a field-by-field guide.
 */

import { FX_PYG_USD } from "@/lib/config";

type RawListing = Omit<Listing, "precioGs">;

const raw: RawListing[] = [
  /* ===================== FEATURED (6) — full 8-image galleries ===================== */
  {
    id: "1",
    slug: "casa-moderna-en-venta-villa-morra-asuncion-a1b2",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa moderna con piscina en Villa Morra",
    descripcion:
      "Residencia de diseño contemporáneo en una de las zonas más cotizadas de Asunción. Amplios espacios integrados, abundante luz natural y terminaciones premium en roble y mármol. Patio con piscina, quincho y jardín consolidado. A pasos de los mejores cafés y colegios de Villa Morra.",
    precioUSD: 485000,
    barrio: "Villa Morra",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 4,
    banos: 4,
    cocheras: 2,
    superficieConstruida: 380,
    superficieTerreno: 520,
    caracteristicas: [
      "Piscina",
      "Quincho",
      "Aire acondicionado",
      "Seguridad 24hs",
      "Jardín",
      "Dependencia de servicio",
    ],
    coordenadas: { lat: -25.2937, lng: -57.5759 },
    imagenes: [
      "prop1-1.jpg",
      "prop1-2.jpg",
      "prop1-3.jpg",
      "prop1-4.jpg",
      "prop1-5.jpg",
      "prop1-6.jpg",
      "prop1-7.jpg",
      "prop1-8.jpg",
    ],
    destacada: true,
    destacadaHasta: "2026-09-30",
    fechaPublicacion: "2026-06-08",
    inmobiliaria: { nombre: "Paraná Propiedades", telefono: "+595 981 123 456" },
  },
  {
    id: "2",
    slug: "departamento-premium-en-venta-carmelitas-asuncion-c3d4",
    operacion: "venta",
    tipo: "departamento",
    titulo: "Departamento premium en torre de Carmelitas",
    descripcion:
      "Unidad de categoría en torre con amenities full sobre Avenida San Martín. Living comedor con ventanal de piso a techo y vista abierta a la ciudad. Cocina equipada y suite principal con vestidor. El edificio ofrece piscina, gimnasio y seguridad permanente.",
    precioUSD: 295000,
    barrio: "Carmelitas",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 165,
    superficieTerreno: 0,
    caracteristicas: [
      "Piscina",
      "Gimnasio",
      "Seguridad 24hs",
      "Aire acondicionado",
      "Ascensor",
      "Balcón",
    ],
    coordenadas: { lat: -25.2841, lng: -57.5912 },
    imagenes: [
      "prop2-1.jpg",
      "prop2-2.jpg",
      "prop2-3.jpg",
      "prop2-4.jpg",
      "prop2-5.jpg",
      "prop2-6.jpg",
      "prop2-7.jpg",
      "prop2-8.jpg",
    ],
    destacada: true,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-05",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "3",
    slug: "duplex-en-venta-las-mercedes-asuncion-e5f6",
    operacion: "venta",
    tipo: "duplex",
    titulo: "Dúplex luminoso en Las Mercedes",
    descripcion:
      "Dúplex de dos plantas en barrio residencial tranquilo y arbolado. Planta baja con living, comedor y cocina abierta; planta alta con tres dormitorios y dos baños. Pequeño patio interno ideal para parrilla. Excelente relación precio-ubicación a minutos del centro.",
    precioUSD: 178000,
    barrio: "Las Mercedes",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 3,
    banos: 3,
    cocheras: 1,
    superficieConstruida: 210,
    superficieTerreno: 240,
    caracteristicas: ["Quincho", "Patio", "Aire acondicionado", "Cocina equipada"],
    coordenadas: { lat: -25.2998, lng: -57.5688 },
    imagenes: [
      "prop3-1.jpg",
      "prop3-2.jpg",
      "prop3-3.jpg",
      "prop3-4.jpg",
      "prop3-5.jpg",
      "prop3-6.jpg",
      "prop3-7.jpg",
      "prop3-8.jpg",
    ],
    destacada: true,
    destacadaHasta: "2026-08-15",
    fechaPublicacion: "2026-06-02",
    inmobiliaria: { nombre: "Hogar Guaraní Inmobiliaria", telefono: "+595 971 444 555" },
  },
  {
    id: "4",
    slug: "terreno-en-venta-luque-central-g7h8",
    operacion: "venta",
    tipo: "terreno",
    titulo: "Terreno en barrio cerrado en Luque",
    descripcion:
      "Lote en barrio cerrado con seguridad y todos los servicios subterráneos. Terreno alto, plano y listo para construir, en zona de fuerte plusvalía cercana al aeropuerto y a la costanera de Luque. Ideal para vivienda familiar de categoría.",
    precioUSD: 92000,
    barrio: "Mora Cué",
    ciudad: "Luque",
    departamento: "Central",
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 600,
    caracteristicas: ["Barrio cerrado", "Seguridad 24hs", "Servicios subterráneos"],
    coordenadas: { lat: -25.2705, lng: -57.4878 },
    imagenes: [
      "prop4-1.jpg",
      "prop4-2.jpg",
      "prop4-3.jpg",
      "prop4-4.jpg",
      "prop4-5.jpg",
      "prop4-6.jpg",
      "prop4-7.jpg",
      "prop4-8.jpg",
    ],
    destacada: true,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-29",
    inmobiliaria: { nombre: "Central Inversiones", telefono: "+595 983 666 777" },
  },
  {
    id: "5",
    slug: "oficina-en-alquiler-recoleta-asuncion-i9j0",
    operacion: "alquiler",
    tipo: "oficina",
    titulo: "Oficina corporativa en Recoleta",
    descripcion:
      "Oficina en planta libre dentro de edificio corporativo sobre Avenida Mariscal López. Espacio flexible con sala de reuniones, kitchenette y baños privados. Cuenta con cocheras, recepción y seguridad. Ideal para estudios profesionales y empresas en crecimiento.",
    precioUSD: 1800,
    barrio: "Recoleta",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 0,
    banos: 2,
    cocheras: 3,
    superficieConstruida: 140,
    superficieTerreno: 0,
    caracteristicas: [
      "Aire acondicionado",
      "Seguridad 24hs",
      "Ascensor",
      "Recepción",
      "Cocheras",
    ],
    coordenadas: { lat: -25.2901, lng: -57.5805 },
    imagenes: [
      "prop5-1.jpg",
      "prop5-2.jpg",
      "prop5-3.jpg",
      "prop5-4.jpg",
      "prop5-5.jpg",
      "prop5-6.jpg",
      "prop5-7.jpg",
      "prop5-8.jpg",
    ],
    destacada: true,
    destacadaHasta: "2026-10-31",
    fechaPublicacion: "2026-05-26",
    inmobiliaria: { nombre: "Mariscal Negocios Inmobiliarios", telefono: "+595 982 888 999" },
  },
  {
    id: "6",
    slug: "casa-en-venta-encarnacion-itapua-k1l2",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa con vista al río en Encarnación",
    descripcion:
      "Casa amplia y soleada a pocas cuadras de la costanera de Encarnación. Diseño funcional de una planta con tres dormitorios, patio con churrasquera y galería techada. Barrio tranquilo, ideal para vivir todo el año o como casa de descanso frente a las playas urbanas.",
    precioUSD: 165000,
    barrio: "San Roque",
    ciudad: "Encarnación",
    departamento: "Itapúa",
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 220,
    superficieTerreno: 400,
    caracteristicas: ["Quincho", "Galería", "Patio", "Aire acondicionado"],
    coordenadas: { lat: -27.3306, lng: -55.8662 },
    imagenes: [
      "prop6-1.jpg",
      "prop6-2.jpg",
      "prop6-3.jpg",
      "prop6-4.jpg",
      "prop6-5.jpg",
      "prop6-6.jpg",
      "prop6-7.jpg",
      "prop6-8.jpg",
    ],
    destacada: true,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-22",
    inmobiliaria: { nombre: "Itapúa Sur Propiedades", telefono: "+595 975 111 222" },
  },

  /* ===================== REST (~30) — reuse pool images ===================== */
  {
    id: "7",
    slug: "casa-en-venta-carmelitas-asuncion-m3n4",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa familiar en Carmelitas",
    descripcion:
      "Casa sólida en zona consolidada de Carmelitas, sobre calle tranquila. Living comedor con buena ventilación, cocina independiente y patio con espacio para piscina. Excelente oportunidad para refaccionar a gusto en un barrio de alta demanda.",
    precioUSD: 320000,
    barrio: "Carmelitas",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 4,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 290,
    superficieTerreno: 450,
    caracteristicas: ["Patio", "Aire acondicionado", "Dependencia de servicio"],
    coordenadas: { lat: -25.2826, lng: -57.5934 },
    imagenes: ["prop1-1.jpg", "prop1-2.jpg", "prop1-8.jpg", "prop1-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-20",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "8",
    slug: "departamento-en-venta-las-mercedes-asuncion-o5p6",
    operacion: "venta",
    tipo: "departamento",
    titulo: "Departamento de 2 dormitorios en Las Mercedes",
    descripcion:
      "Departamento práctico y luminoso ideal para parejas o inversores. Living comedor integrado a cocina, dos dormitorios y balcón con vista despejada. Edificio con ascensor y seguridad, a metros de comercios y paradas de transporte.",
    precioUSD: 118000,
    barrio: "Las Mercedes",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 92,
    superficieTerreno: 0,
    caracteristicas: ["Ascensor", "Seguridad 24hs", "Balcón", "Aire acondicionado"],
    coordenadas: { lat: -25.3012, lng: -57.5701 },
    imagenes: ["prop2-1.jpg", "prop2-3.jpg", "prop2-5.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-18",
    inmobiliaria: { nombre: "Paraná Propiedades", telefono: "+595 981 123 456" },
  },
  {
    id: "9",
    slug: "departamento-en-alquiler-villa-morra-asuncion-q7r8",
    operacion: "alquiler",
    tipo: "departamento",
    titulo: "Departamento amoblado en Villa Morra",
    descripcion:
      "Departamento amoblado listo para mudarse, en el corazón de Villa Morra. Un dormitorio en suite, living confortable y cocina equipada. Edificio con piscina y gimnasio, ideal para ejecutivos. Incluye una cochera fija.",
    precioUSD: 850,
    barrio: "Villa Morra",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 1,
    banos: 1,
    cocheras: 1,
    superficieConstruida: 65,
    superficieTerreno: 0,
    caracteristicas: ["Amoblado", "Piscina", "Gimnasio", "Seguridad 24hs", "Ascensor"],
    coordenadas: { lat: -25.2951, lng: -57.5742 },
    imagenes: ["prop2-2.jpg", "prop2-4.jpg", "prop2-6.jpg", "prop2-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-10",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "10",
    slug: "casa-en-alquiler-mburucuya-asuncion-s9t0",
    operacion: "alquiler",
    tipo: "casa",
    titulo: "Casa en alquiler en Mburucuyá",
    descripcion:
      "Casa de tres dormitorios en barrio residencial y verde de Mburucuyá. Amplio living, cocina con office y patio con quincho. Ideal para familias que buscan tranquilidad sin alejarse de los accesos a Asunción.",
    precioUSD: 1100,
    barrio: "Mburucuyá",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 200,
    superficieTerreno: 360,
    caracteristicas: ["Quincho", "Patio", "Aire acondicionado", "Jardín"],
    coordenadas: { lat: -25.2614, lng: -57.5538 },
    imagenes: ["prop1-1.jpg", "prop1-7.jpg", "prop3-2.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-09",
    inmobiliaria: { nombre: "Hogar Guaraní Inmobiliaria", telefono: "+595 971 444 555" },
  },
  {
    id: "11",
    slug: "casa-en-venta-recoleta-asuncion-u1v2",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa de categoría en Recoleta",
    descripcion:
      "Imponente residencia en Recoleta con jardín frontal y piscina. Cuatro suites, escritorio, living de doble altura y quincho cerrado con parrilla. Construcción de primera calidad en una de las zonas más exclusivas de la capital.",
    precioUSD: 620000,
    barrio: "Recoleta",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 4,
    banos: 5,
    cocheras: 3,
    superficieConstruida: 460,
    superficieTerreno: 700,
    caracteristicas: [
      "Piscina",
      "Quincho",
      "Seguridad 24hs",
      "Aire acondicionado",
      "Jardín",
      "Dependencia de servicio",
    ],
    coordenadas: { lat: -25.2918, lng: -57.5821 },
    imagenes: ["prop1-1.jpg", "prop1-2.jpg", "prop1-3.jpg", "prop1-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-15",
    inmobiliaria: { nombre: "Mariscal Negocios Inmobiliarios", telefono: "+595 982 888 999" },
  },
  {
    id: "12",
    slug: "departamento-en-venta-recoleta-asuncion-w3x4",
    operacion: "venta",
    tipo: "departamento",
    titulo: "Departamento de 3 dormitorios en Recoleta",
    descripcion:
      "Espacioso departamento con planta funcional y excelente iluminación. Tres dormitorios, dependencia, balcón terraza y dos cocheras. Edificio con amenities completos sobre avenida principal, próximo a shoppings y restaurantes.",
    precioUSD: 245000,
    barrio: "Recoleta",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 145,
    superficieTerreno: 0,
    caracteristicas: ["Piscina", "Gimnasio", "Seguridad 24hs", "Balcón", "Ascensor"],
    coordenadas: { lat: -25.2889, lng: -57.5849 },
    imagenes: ["prop2-1.jpg", "prop2-2.jpg", "prop2-8.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-12",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "13",
    slug: "terreno-en-venta-san-lorenzo-central-y5z6",
    operacion: "venta",
    tipo: "terreno",
    titulo: "Terreno comercial sobre Ruta en San Lorenzo",
    descripcion:
      "Excelente terreno con frente sobre avenida de alto tránsito en San Lorenzo. Apto para emprendimiento comercial o edificio de renta. Zona en pleno desarrollo con todos los servicios disponibles. Gran oportunidad de inversión.",
    precioUSD: 135000,
    barrio: "Centro",
    ciudad: "San Lorenzo",
    departamento: "Central",
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 800,
    caracteristicas: ["Esquina", "Apto comercial", "Sobre avenida"],
    coordenadas: { lat: -25.3397, lng: -57.5089 },
    imagenes: ["prop4-1.jpg", "prop4-3.jpg", "prop4-5.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-10",
    inmobiliaria: { nombre: "Central Inversiones", telefono: "+595 983 666 777" },
  },
  {
    id: "14",
    slug: "casa-en-venta-lambare-central-a7b8",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa a estrenar en Lambaré",
    descripcion:
      "Casa nueva de diseño moderno en barrio tranquilo de Lambaré. Tres dormitorios, suite principal con vestidor, cocina abierta y patio con espacio para piscina. Terminaciones de calidad, lista para habitar.",
    precioUSD: 195000,
    barrio: "Santa Rosa",
    ciudad: "Lambaré",
    departamento: "Central",
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 185,
    superficieTerreno: 300,
    caracteristicas: ["Quincho", "Patio", "Aire acondicionado", "A estrenar"],
    coordenadas: { lat: -25.3486, lng: -57.6098 },
    imagenes: ["prop3-1.jpg", "prop3-3.jpg", "prop3-5.jpg", "prop3-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-07",
    inmobiliaria: { nombre: "Hogar Guaraní Inmobiliaria", telefono: "+595 971 444 555" },
  },
  {
    id: "15",
    slug: "departamento-en-alquiler-las-mercedes-asuncion-c9d0",
    operacion: "alquiler",
    tipo: "departamento",
    titulo: "Monoambiente en Las Mercedes",
    descripcion:
      "Monoambiente moderno ideal para estudiantes o profesionales jóvenes. Espacio optimizado con cocina integrada y baño completo. Edificio con seguridad y ascensor, cerca de universidades y del microcentro.",
    precioUSD: 420,
    barrio: "Las Mercedes",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 1,
    banos: 1,
    cocheras: 0,
    superficieConstruida: 38,
    superficieTerreno: 0,
    caracteristicas: ["Ascensor", "Seguridad 24hs", "Amoblado"],
    coordenadas: { lat: -25.3025, lng: -57.5666 },
    imagenes: ["prop2-3.jpg", "prop2-5.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-06",
    inmobiliaria: { nombre: "Paraná Propiedades", telefono: "+595 981 123 456" },
  },
  {
    id: "16",
    slug: "oficina-en-venta-villa-morra-asuncion-e1f2",
    operacion: "venta",
    tipo: "oficina",
    titulo: "Oficina en torre empresarial de Villa Morra",
    descripcion:
      "Oficina en piso alto con vista panorámica, en torre empresarial de primer nivel. Planta flexible apta para subdividir, con baños privados y office. Edificio con cocheras, recepción y generador propio.",
    precioUSD: 210000,
    barrio: "Villa Morra",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 0,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 120,
    superficieTerreno: 0,
    caracteristicas: ["Aire acondicionado", "Seguridad 24hs", "Ascensor", "Recepción"],
    coordenadas: { lat: -25.2962, lng: -57.5771 },
    imagenes: ["prop5-1.jpg", "prop5-3.jpg", "prop5-6.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-08",
    inmobiliaria: { nombre: "Mariscal Negocios Inmobiliarios", telefono: "+595 982 888 999" },
  },
  {
    id: "17",
    slug: "local-en-alquiler-centro-asuncion-g3h4",
    operacion: "alquiler",
    tipo: "local",
    titulo: "Local comercial sobre Palma, Centro",
    descripcion:
      "Local a la calle sobre la peatonal Palma, en pleno microcentro de Asunción. Amplio salón, depósito y baño. Gran vidriera y alto flujo peatonal, ideal para comercio o showroom. Excelente exposición de marca.",
    precioUSD: 1500,
    barrio: "Centro",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 0,
    banos: 1,
    cocheras: 0,
    superficieConstruida: 110,
    superficieTerreno: 0,
    caracteristicas: ["A la calle", "Vidriera", "Depósito", "Apto comercial"],
    coordenadas: { lat: -25.2818, lng: -57.6354 },
    imagenes: ["prop5-2.jpg", "prop5-4.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-04",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "18",
    slug: "casa-en-venta-san-lorenzo-central-i5j6",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa amplia en San Lorenzo",
    descripcion:
      "Casa de generosas dimensiones en barrio consolidado de San Lorenzo. Cuatro dormitorios, living comedor, cocina con despensa y amplio patio arbolado con quincho. Ideal para familia numerosa, con cochera para tres vehículos.",
    precioUSD: 168000,
    barrio: "Villa del Maestro",
    ciudad: "San Lorenzo",
    departamento: "Central",
    dormitorios: 4,
    banos: 3,
    cocheras: 3,
    superficieConstruida: 240,
    superficieTerreno: 480,
    caracteristicas: ["Quincho", "Patio", "Jardín", "Aire acondicionado"],
    coordenadas: { lat: -25.3419, lng: -57.5076 },
    imagenes: ["prop1-1.jpg", "prop1-4.jpg", "prop1-7.jpg", "prop6-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-05",
    inmobiliaria: { nombre: "Central Inversiones", telefono: "+595 983 666 777" },
  },
  {
    id: "19",
    slug: "departamento-en-venta-mariano-roque-alonso-central-k7l8",
    operacion: "venta",
    tipo: "departamento",
    titulo: "Departamento nuevo en Mariano Roque Alonso",
    descripcion:
      "Departamento a estrenar en complejo con áreas comunes, sobre acceso a Mariano Roque Alonso. Dos dormitorios, balcón y cochera. Complejo con piscina, salón de eventos y seguridad. Gran oportunidad de inversión o primera vivienda.",
    precioUSD: 98000,
    barrio: "Santa María",
    ciudad: "Mariano Roque Alonso",
    departamento: "Central",
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 78,
    superficieTerreno: 0,
    caracteristicas: ["Piscina", "Seguridad 24hs", "Balcón", "A estrenar", "Salón de eventos"],
    coordenadas: { lat: -25.2015, lng: -57.5326 },
    imagenes: ["prop2-1.jpg", "prop2-4.jpg", "prop2-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-01",
    inmobiliaria: { nombre: "Hogar Guaraní Inmobiliaria", telefono: "+595 971 444 555" },
  },
  {
    id: "20",
    slug: "casa-en-venta-luque-central-m9n0",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa con piscina en Luque",
    descripcion:
      "Casa moderna de una planta con piscina y quincho, en barrio residencial de Luque. Tres dormitorios en suite, living integrado y galería con vista al jardín. Construcción reciente con excelentes terminaciones.",
    precioUSD: 215000,
    barrio: "Laurelty",
    ciudad: "Luque",
    departamento: "Central",
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 230,
    superficieTerreno: 420,
    caracteristicas: ["Piscina", "Quincho", "Galería", "Aire acondicionado", "Jardín"],
    coordenadas: { lat: -25.2668, lng: -57.4943 },
    imagenes: ["prop1-1.jpg", "prop1-7.jpg", "prop3-1.jpg", "prop3-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-28",
    inmobiliaria: { nombre: "Central Inversiones", telefono: "+595 983 666 777" },
  },
  {
    id: "21",
    slug: "duplex-en-venta-fernando-de-la-mora-central-o1p2",
    operacion: "venta",
    tipo: "duplex",
    titulo: "Dúplex moderno en Fernando de la Mora",
    descripcion:
      "Dúplex a estrenar en barrio tranquilo de Fernando de la Mora. Diseño actual con living de doble altura, tres dormitorios y patio con churrasquera. Cochera para dos autos y excelente ubicación cerca de avenidas principales.",
    precioUSD: 142000,
    barrio: "Zona Norte",
    ciudad: "Fernando de la Mora",
    departamento: "Central",
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 175,
    superficieTerreno: 220,
    caracteristicas: ["Quincho", "Patio", "A estrenar", "Aire acondicionado"],
    coordenadas: { lat: -25.3289, lng: -57.5219 },
    imagenes: ["prop3-1.jpg", "prop3-2.jpg", "prop3-4.jpg", "prop3-6.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-25",
    inmobiliaria: { nombre: "Paraná Propiedades", telefono: "+595 981 123 456" },
  },
  {
    id: "22",
    slug: "terreno-en-venta-capiata-central-q3r4",
    operacion: "venta",
    tipo: "terreno",
    titulo: "Terreno amplio en Capiatá",
    descripcion:
      "Terreno de buenas dimensiones en zona residencial de Capiatá, ideal para construir vivienda familiar. Calle asfaltada, energía eléctrica y agua corriente disponibles. Entorno tranquilo y en crecimiento, con buena conexión a la Ruta.",
    precioUSD: 48000,
    barrio: "Mbocayaty",
    ciudad: "Capiatá",
    departamento: "Central",
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 720,
    caracteristicas: ["Calle asfaltada", "Servicios disponibles"],
    coordenadas: { lat: -25.3553, lng: -57.3456 },
    imagenes: ["prop4-2.jpg", "prop4-4.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-19",
    inmobiliaria: { nombre: "Central Inversiones", telefono: "+595 983 666 777" },
  },
  {
    id: "23",
    slug: "departamento-en-alquiler-recoleta-asuncion-s5t6",
    operacion: "alquiler",
    tipo: "departamento",
    titulo: "Departamento de 2 dormitorios en Recoleta",
    descripcion:
      "Cómodo departamento en zona premium de Recoleta, próximo a shoppings y restaurantes. Dos dormitorios, living comedor amplio y balcón. Edificio con piscina, gimnasio y seguridad permanente. Incluye una cochera.",
    precioUSD: 980,
    barrio: "Recoleta",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 88,
    superficieTerreno: 0,
    caracteristicas: ["Piscina", "Gimnasio", "Seguridad 24hs", "Balcón", "Ascensor"],
    coordenadas: { lat: -25.2895, lng: -57.5862 },
    imagenes: ["prop2-2.jpg", "prop2-5.jpg", "prop2-8.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-11",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "24",
    slug: "casa-en-venta-mariano-roque-alonso-central-u7v8",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa quinta en Mariano Roque Alonso",
    descripcion:
      "Casa quinta con amplio parque arbolado y piscina, ideal para descanso o vivienda permanente. Tres dormitorios, quincho cerrado y churrasquera. Terreno de gran superficie en zona tranquila, a minutos de la ciudad.",
    precioUSD: 230000,
    barrio: "San Antonio",
    ciudad: "Mariano Roque Alonso",
    departamento: "Central",
    dormitorios: 3,
    banos: 3,
    cocheras: 4,
    superficieConstruida: 260,
    superficieTerreno: 1200,
    caracteristicas: ["Piscina", "Quincho", "Jardín", "Parque", "Aire acondicionado"],
    coordenadas: { lat: -25.1987, lng: -57.5398 },
    imagenes: ["prop1-1.jpg", "prop1-7.jpg", "prop6-1.jpg", "prop6-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-16",
    inmobiliaria: { nombre: "Hogar Guaraní Inmobiliaria", telefono: "+595 971 444 555" },
  },
  {
    id: "25",
    slug: "departamento-en-venta-ciudad-del-este-alto-parana-w9x0",
    operacion: "venta",
    tipo: "departamento",
    titulo: "Departamento céntrico en Ciudad del Este",
    descripcion:
      "Departamento bien ubicado en el centro de Ciudad del Este, cerca del área comercial. Dos dormitorios, living comedor y cocina equipada. Edificio con seguridad y ascensor. Ideal para vivienda o renta por su ubicación estratégica.",
    precioUSD: 105000,
    barrio: "Área 1",
    ciudad: "Ciudad del Este",
    departamento: "Alto Paraná",
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 95,
    superficieTerreno: 0,
    caracteristicas: ["Ascensor", "Seguridad 24hs", "Aire acondicionado", "Balcón"],
    coordenadas: { lat: -25.5096, lng: -54.6113 },
    imagenes: ["prop2-1.jpg", "prop2-6.jpg", "prop2-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-14",
    inmobiliaria: { nombre: "Este Inmobiliaria", telefono: "+595 973 333 444" },
  },
  {
    id: "26",
    slug: "casa-en-venta-manora-asuncion-y1z2",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa residencial en Manorá",
    descripcion:
      "Casa de estilo clásico en el tranquilo barrio Manorá. Tres dormitorios, escritorio, living comedor y patio con jardín consolidado. Zona arbolada y segura, ideal para familias que valoran la tranquilidad cerca del shopping.",
    precioUSD: 285000,
    barrio: "Manorá",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 245,
    superficieTerreno: 380,
    caracteristicas: ["Jardín", "Patio", "Aire acondicionado", "Dependencia de servicio"],
    coordenadas: { lat: -25.2607, lng: -57.5419 },
    imagenes: ["prop1-1.jpg", "prop1-2.jpg", "prop1-5.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-11",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "27",
    slug: "local-en-venta-villa-morra-asuncion-a3b4",
    operacion: "venta",
    tipo: "local",
    titulo: "Local comercial en Villa Morra",
    descripcion:
      "Local a la calle en zona de alto tránsito comercial de Villa Morra. Salón amplio, entrepiso y baño. Ideal para gastronomía, oficina comercial o tienda. Excelente visibilidad sobre avenida con estacionamiento cercano.",
    precioUSD: 175000,
    barrio: "Villa Morra",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 0,
    banos: 2,
    cocheras: 1,
    superficieConstruida: 130,
    superficieTerreno: 0,
    caracteristicas: ["A la calle", "Entrepiso", "Apto comercial", "Aire acondicionado"],
    coordenadas: { lat: -25.2944, lng: -57.5728 },
    imagenes: ["prop5-2.jpg", "prop5-5.jpg", "prop5-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-07",
    inmobiliaria: { nombre: "Mariscal Negocios Inmobiliarios", telefono: "+595 982 888 999" },
  },
  {
    id: "28",
    slug: "casa-en-alquiler-lambare-central-c5d6",
    operacion: "alquiler",
    tipo: "casa",
    titulo: "Casa en alquiler en Lambaré",
    descripcion:
      "Casa cómoda de tres dormitorios en barrio residencial de Lambaré. Living comedor, cocina independiente y patio con quincho. Cochera para dos vehículos. Cerca de colegios, comercios y accesos a Asunción.",
    precioUSD: 750,
    barrio: "San Pedro",
    ciudad: "Lambaré",
    departamento: "Central",
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 165,
    superficieTerreno: 300,
    caracteristicas: ["Quincho", "Patio", "Aire acondicionado"],
    coordenadas: { lat: -25.3531, lng: -57.6041 },
    imagenes: ["prop3-1.jpg", "prop3-5.jpg", "prop6-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-06-03",
    inmobiliaria: { nombre: "Hogar Guaraní Inmobiliaria", telefono: "+595 971 444 555" },
  },
  {
    id: "29",
    slug: "departamento-en-venta-jara-asuncion-e7f8",
    operacion: "venta",
    tipo: "departamento",
    titulo: "Departamento de 1 dormitorio en Jara",
    descripcion:
      "Departamento ideal para inversión en el dinámico barrio Jara. Un dormitorio, living comedor integrado a cocina y balcón. Edificio con seguridad, gimnasio y rooftop. Cerca de universidades y zona gastronómica.",
    precioUSD: 82000,
    barrio: "Jara",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 1,
    banos: 1,
    cocheras: 1,
    superficieConstruida: 52,
    superficieTerreno: 0,
    caracteristicas: ["Gimnasio", "Seguridad 24hs", "Balcón", "Ascensor", "Rooftop"],
    coordenadas: { lat: -25.2829, lng: -57.5689 },
    imagenes: ["prop2-3.jpg", "prop2-4.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-30",
    inmobiliaria: { nombre: "Paraná Propiedades", telefono: "+595 981 123 456" },
  },
  {
    id: "30",
    slug: "casa-en-venta-ykua-sati-asuncion-g9h0",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa moderna en Ykua Satí",
    descripcion:
      "Casa de diseño minimalista en el exclusivo barrio Ykua Satí. Amplios ambientes integrados, cuatro suites, piscina y quincho gourmet. Domótica y excelentes terminaciones. Una propiedad para disfrutar en una de las mejores zonas de Asunción.",
    precioUSD: 540000,
    barrio: "Ykua Satí",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 4,
    banos: 5,
    cocheras: 3,
    superficieConstruida: 410,
    superficieTerreno: 600,
    caracteristicas: [
      "Piscina",
      "Quincho",
      "Domótica",
      "Seguridad 24hs",
      "Aire acondicionado",
      "Jardín",
    ],
    coordenadas: { lat: -25.2741, lng: -57.5613 },
    imagenes: ["prop1-1.jpg", "prop1-2.jpg", "prop1-3.jpg", "prop1-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-27",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "31",
    slug: "oficina-en-alquiler-carmelitas-asuncion-i1j2",
    operacion: "alquiler",
    tipo: "oficina",
    titulo: "Oficina boutique en Carmelitas",
    descripcion:
      "Oficina lista para usar en edificio boutique de Carmelitas. Dos privados, sala de reuniones y recepción. Incluye cocheras y mobiliario básico. Ambiente profesional y tranquilo, ideal para estudios y consultoras.",
    precioUSD: 1200,
    barrio: "Carmelitas",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 0,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 95,
    superficieTerreno: 0,
    caracteristicas: ["Amoblado", "Aire acondicionado", "Seguridad 24hs", "Recepción"],
    coordenadas: { lat: -25.2833, lng: -57.5921 },
    imagenes: ["prop5-1.jpg", "prop5-6.jpg", "prop5-8.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-24",
    inmobiliaria: { nombre: "Mariscal Negocios Inmobiliarios", telefono: "+595 982 888 999" },
  },
  {
    id: "32",
    slug: "terreno-en-venta-villa-morra-asuncion-k3l4",
    operacion: "venta",
    tipo: "terreno",
    titulo: "Terreno para edificio en Villa Morra",
    descripcion:
      "Terreno de excelente ubicación en Villa Morra, apto para desarrollo de edificio en altura según normativa vigente. Zona de máxima demanda residencial y comercial. Oportunidad única para desarrolladores e inversores.",
    precioUSD: 290000,
    barrio: "Villa Morra",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    superficieConstruida: 0,
    superficieTerreno: 540,
    caracteristicas: ["Apto edificio", "Esquina", "Zona premium"],
    coordenadas: { lat: -25.2955, lng: -57.5766 },
    imagenes: ["prop4-1.jpg", "prop4-6.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-21",
    inmobiliaria: { nombre: "Central Inversiones", telefono: "+595 983 666 777" },
  },
  {
    id: "33",
    slug: "casa-en-venta-fernando-de-la-mora-central-m5n6",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa familiar en Fernando de la Mora",
    descripcion:
      "Casa de tres dormitorios en barrio tranquilo y consolidado de Fernando de la Mora. Living comedor, cocina con office y patio amplio con espacio para piscina. Buena oportunidad para familia, con cochera para dos autos.",
    precioUSD: 138000,
    barrio: "Zona Sur",
    ciudad: "Fernando de la Mora",
    departamento: "Central",
    dormitorios: 3,
    banos: 2,
    cocheras: 2,
    superficieConstruida: 170,
    superficieTerreno: 320,
    caracteristicas: ["Patio", "Aire acondicionado", "Quincho"],
    coordenadas: { lat: -25.3361, lng: -57.5238 },
    imagenes: ["prop3-1.jpg", "prop3-3.jpg", "prop6-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-17",
    inmobiliaria: { nombre: "Hogar Guaraní Inmobiliaria", telefono: "+595 971 444 555" },
  },
  {
    id: "34",
    slug: "departamento-en-venta-villa-morra-asuncion-o7p8",
    operacion: "venta",
    tipo: "departamento",
    titulo: "Departamento de lujo en Villa Morra",
    descripcion:
      "Exclusivo departamento en torre de categoría con amenities premium. Tres suites, living comedor amplio, lavadero y dos terrazas con vista a la ciudad. Edificio con piscina infinity, spa y seguridad de primer nivel.",
    precioUSD: 340000,
    barrio: "Villa Morra",
    ciudad: "Asunción",
    departamento: "Capital",
    dormitorios: 3,
    banos: 4,
    cocheras: 2,
    superficieConstruida: 190,
    superficieTerreno: 0,
    caracteristicas: [
      "Piscina",
      "Gimnasio",
      "Spa",
      "Seguridad 24hs",
      "Balcón",
      "Ascensor",
    ],
    coordenadas: { lat: -25.2948, lng: -57.5754 },
    imagenes: ["prop2-1.jpg", "prop2-2.jpg", "prop2-5.jpg", "prop2-8.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-13",
    inmobiliaria: { nombre: "Asunción Realty", telefono: "+595 985 222 333" },
  },
  {
    id: "35",
    slug: "casa-en-alquiler-san-lorenzo-central-q9r0",
    operacion: "alquiler",
    tipo: "casa",
    titulo: "Casa en alquiler en San Lorenzo",
    descripcion:
      "Casa práctica de dos dormitorios en barrio residencial de San Lorenzo. Living comedor, cocina y patio con galería. Cochera techada. Cerca de la Universidad Nacional y de avenidas con transporte público.",
    precioUSD: 600,
    barrio: "Barcequillo",
    ciudad: "San Lorenzo",
    departamento: "Central",
    dormitorios: 2,
    banos: 1,
    cocheras: 1,
    superficieConstruida: 110,
    superficieTerreno: 240,
    caracteristicas: ["Galería", "Patio", "Aire acondicionado"],
    coordenadas: { lat: -25.3458, lng: -57.5132 },
    imagenes: ["prop6-1.jpg", "prop6-7.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-31",
    inmobiliaria: { nombre: "Central Inversiones", telefono: "+595 983 666 777" },
  },
  {
    id: "36",
    slug: "duplex-en-venta-luque-central-s1t2",
    operacion: "venta",
    tipo: "duplex",
    titulo: "Dúplex a estrenar en Luque",
    descripcion:
      "Dúplex nuevo de excelente distribución en barrio tranquilo de Luque. Planta baja social con cocina abierta y planta alta con tres dormitorios. Patio con churrasquera y cochera para dos autos. Listo para habitar.",
    precioUSD: 128000,
    barrio: "Itá Enramada",
    ciudad: "Luque",
    departamento: "Central",
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    superficieConstruida: 165,
    superficieTerreno: 200,
    caracteristicas: ["Quincho", "Patio", "A estrenar", "Aire acondicionado"],
    coordenadas: { lat: -25.2719, lng: -57.4881 },
    imagenes: ["prop3-1.jpg", "prop3-2.jpg", "prop3-6.jpg", "prop3-8.jpg"],
    destacada: false,
    destacadaHasta: null,
    fechaPublicacion: "2026-05-23",
    inmobiliaria: { nombre: "Hogar Guaraní Inmobiliaria", telefono: "+595 971 444 555" },
  },
];

/** Final typed seed array — precioGs derived from precioUSD at the fixed rate. */
export const listings: Listing[] = raw.map((l) => ({
  ...l,
  precioGs: Math.round(l.precioUSD * FX_PYG_USD),
}));
